### PR TITLE
:globe_with_meridians:  add german translation

### PR DESCRIPTION
**Pull request by FineFindus**
Translates this project into German. I wasn't able to build the project or generate a template file, so I based the translation on `pt_BR.po`.

### CODE REVIEW

**Comment by CleoMenezesJr** [comment]
Hello and thank you very much for your contribution, but because you based the creation of the German translation on the Portuguese translation causes this translation to be dated.
The problem is that when @rffontenelle contributed this translation, the application was a little different and many things changed. Unfortunately, accepting this translation would be to add something that would not be functional.

Again, thank you so much for your time trying to contribute to the project.

**Comment by rffontenelle** [comment]
To update the template and the PO file, use:

```
meson . build
# installing dependencies might be required
ninja -C build <tab><tab>
# and look for target <something>-update-po
```

**Comment by FineFindus** [comment]
After fixing a bug with a missing file (#42), I managed to generate the template file, and it should now be up-to-date.

Maybe it's a good idea to instructions on how to build the template to the README?

**Comment by CleoMenezesJr** [comment]
> After fixing a bug with a missing file (#42), I managed to generate the template file, and it should now be up-to-date.
> 
> Maybe it's a good idea to instructions on how to build the template to the README?

Cool! It certainly should be. Particularly, I don't know anything about translation, consequently I never documented anything about it. haha

**Comment by rffontenelle** [comment]
@CleoMenezesJr Any intention to use a translation platform any time soon? If not, then it would be interesting to document it.

**Comment by CleoMenezesJr** [comment]
> @CleoMenezesJr Any intention to use a translation platform any time soon? If not, then it would be interesting to document it.

It could be interesting. I don't understand well about the platforms, but I could study about them. Any suggestion?

**Comment by rffontenelle** [comment]
For apps in GNOME Incubator, GNOME Circle, etc., I recommend [Damned Lies](l10n.gnome.org/). For other cases, I recommend using [Hosted Weblate](https://hosted.weblate.org) because it has a Libre plan that is free (as in free beer) for free/libre software (See [hosting prices](https://weblate.org/en/hosting/)).

**Review by CleoMenezesJr — APPROVED** [review]

**Pull request merged**
